### ISSUE TITLE
Make Hot Reloading optional

### ISSUE THREAD

**Issue by rriveras** [vercel/micro-dev#10]
First, thanks for this great tool, and congratulations for the release, the upgrade was a snap.

The only problem I have is with hot reloading for a couple of reasons. First, I use `micro` to write/remove a lot of temp files, and second, I use it with websocket connections.

This mean that my app keep crashing or hanging connections in development. 
It would be great if you could make it optional.

Thanks!

**Comment by leo** [comment]
Sounds like a good idea to me!

**Comment by leo** [comment]
Since [1.1.0](https://github.com/zeit/micro-dev/releases/tag/1.1.0), you can use `--cold`! 😊
