### ISSUE TITLE
res.headersSent is false

### ISSUE THREAD

**Issue by ramiel** [vercel/micro-dev#12]
If I start the project with micro-dev, when I use the send function the `res.headersSent` is false. With micro it's true. Why?

**Comment by timneutkens** [comment]
That shouldn't happen 🤔 It might be related to the logger that overrides `res.end` 🤔

**Comment by sammdec** [comment]
Yeah I'm getting similar issues when using `micro-router`, the server hangs until the docket hangs up.

**Comment by leo** [comment]
@samjbmason You mean `microrouter`?

**Comment by sammdec** [comment]
@leo yeah that's right and I have even used your updated version from the PR you submitted but still with the same results
