### ISSUE TITLE
Babel support?

### ISSUE THREAD

**Issue by Obiwarn** [vercel/micro-dev#17]
Probably very noob question, but how do I use that with Babel?

So far I used babel-watch in the script. And called micro programmatically.

**Comment by leo** [comment]
Use a build tool like Gulp or Webpack + Babel that transpiles and bundles your source code into a directory and then do: `micro-dev <output-dir>`

**Comment by Obiwarn** [comment]
thanks for answering.

this is probably overkill just to get micro-dev. i hoped there was a more elegant solution. like in the Minimum Viable Async example from rauchg: https://gist.github.com/pid/e922b18a944184d881e5164120db2a65

**Comment by leo** [comment]
Async and await work on the latest Node.js version by default. The readme shows this...

**Comment by Obiwarn** [comment]
...and keeping Babel just for the ES6 import modules is probably useless.

Dang. Now I have to refactor all my imports back to require. 😑



2017-08-07 16:17 GMT+02:00 Leo Lamprecht <notifications@github.com>:

**Comment by leo** [comment]
Yea... 😊 As the repo states it, at the current state of Node.js (which supports most of ES2015 already), transpilation doesn‘t make much sense server-side.

**Comment by fmiras** [comment]
I'm working with micro-dev & PhantomJS to make some webscrappers workers. The thing is that [Phantom supports very few ES2015 features](https://stackoverflow.com/questions/37629774/does-phantomjs-support-es6-for-serving-angularjs-app-to-crawlers-and-bots) (something about of 10%) so I want to still use Babel and of course, not just for import statements but now I have the work of running `npm run build` every time I want micro-dev to hot-reload and If I want to automatically build the source code I have to spawn 2 processes, micro-dev and webpack and that isn't efficient. Can we reopen this issue to find a solution for this? I was thinking of making a micro-dev support programmatically API as same micro does or building a webpack-plugin for it.

**Comment by awei01** [comment]
Hi, this might be a naive solution, but it seems to be working:

```
// index.js
require('babel-register')
const foo = require('./foo').default

module.exports = function (req, res) {
  const value = foo()
  console.log('serving stuff', value)
  res.end("Hello, world " + value)
}

```

```
// foo.js
export default () {
  return 'foo value'
}
```

then just `micro index.js` or `micro-dev index.js`

**Comment by vlastv** [comment]
I, too, am waiting for a normal decision and while I launch it as:
```sh
$ ./node_modules/.bin/babel-node ./node_modules/.bin/micro-dev ...
```
