### ISSUE TITLE
ENV vars support

### ISSUE THREAD

**Issue by tamagokun** [vercel/micro-dev#18]
I'm a huge fan of having a `.env` file locally, or specifying variables and "dotenv" files in now.json.

However, this of course is only supported once deployed to now, but it would be great to have support for this in dev without adding in something extra such as `dotenv` or the like.

Would it make sense to add that to `micro-dev`? We could use something like https://github.com/sergiodxa/now-env fairly easily I think.

**Comment by leo** [comment]
Sounds like an interesting idea to me.

I'll keep this issue open for a bit to see if anyone else needs this. Let's see! 👍

**Comment by dopry** [comment]
Storing config in a file to be read by you apps is a bit of an anti-pattern.  see: https://12factor.net/config

Personally I just source my vars into environment variables and use process.env.* || 'default' for all my configs. It's extremely portable and doesn't run as much risk of committing sensitive info to your repo.

**Comment by tamagokun** [comment]
I'm not referring to storing config, but storing environment variables. I believe projects such as [dotenv](https://www.npmjs.com/package/dotenv) are a direct result of 12-factor apps.

If I can specify environment variables through `now.json` or `package.json` (here: https://zeit.co/docs/getting-started/enviornment-variables) it would be extremely convenient to have those loaded automatically when running `mirco-dev` locally.

**Comment by dopry** [comment]
What are you storing in the environment variables if not config? If the
value effect the operation of your app in any way, they're config. Projects
like dot-env are anti-thetical to 12 factors. 12 Factors specifically
recommends that you do not use config files, but use environment variables
instead. The goal is to save your app from having the responsibility of
reading a file. If you put your env vars in a file that your app has to
read, you're doing the opposite of what the 12 Factors guidance recommends.

In purist 12 Factor App, setting environment variables should be external
to your app. You should source your environment prior to starting your app
for local development. In a hosting environment, they should be injected in
the environment by the hosting platform.

does that make sense?

I do understand the convenience, maybe it would be good for micro-dev, but
not micro.

**Comment by tamagokun** [comment]
Makes perfect sense. I think we are talking about the same thing/idea differently.

I don't condone loading config through files, it should be done through environment variables. However, managing apps that need to have several different API keys and what-not to power the app will most definitely constitute some sort of _storage_ to make development and deployment sane. Not saying that these should be "loaded" by the app, but that these environment variables are stored, and should be sourced as environment variables before the app starts.

`now.sh` makes it easy to do this for production through now.json or package.json, so why not provide the same convenience to `micro-dev`? This would ultimately allow people to not need to use something like `dotenv`, which I think is a plus.

Splitting `micro` and `micro-dev` I think is brilliant, and makes it easier to add DX features into the lib.

However, just out of curiosity, how do you manage environment variables now? Using the `dotenv` style file format, you can't just do `source .env`, is there a util that you use?

**Comment by mwickett** [comment]
+1 from me for reading in variables from `now.json` - I came across this thread while searching through Micro documentation to find an answer. For now, I'll just use dotenv

**Comment by dopry** [comment]
@tamagokun why can't I just source my environment. that is exactly what I do.

**Comment by gunar** [comment]
Even if we do load our env variables from `now.json`, all we would have in them is `@references_to_variables_hosted_in_zeit`.

**Comment by lewisl9029** [comment]
I made a PR to enable setting `micro-dev`'s cli flags using env vars since I wanted that functionality for use with docker-compose: https://github.com/zeit/micro-dev/pull/44

I don't think it's quite the same feature as what people are asking for here (it sounds like this issue is more about loading arbitrary env vars for consumption in app, rather than using env vars to configure `micro-dev` itself?). But it does present another use case for being able to load env vars from files (to configure `micro-dev` itself through the same env var loading mechanism).

**Comment by sbrichardson** [comment]
@tamagokun - Just a note, if you must use a .env file (which I agree is anti-pattern) you can avoid using the dotenv npm addon, by just adding "export " to each line in a typical .env file and sourcing it before starting the server in your start script.

```
test="123"
key="abc"

# becomes

export test="123"
export key="abc"

# then just source the file in the command line script before starting server
# package.json / scripts

"start": "source ./.env && ...start server"

```

**Comment by leo** [comment]
Just add [now-env](https://github.com/zeit/now-env):

```js
require('now-env')
```

That's it!

**Comment by wiiiimm** [comment]
@leo can `now-env` in mico support `--local-config now-something.json`?
