### ISSUE TITLE
Send SIGUSR2 signal on restart like nodemon?

### ISSUE THREAD

**Issue by ericf** [vercel/micro-dev#21]
Would it be possible to add a some signal, e.g. `SIGUSR2` before a restart to allow a micro server to perform some cleanup? `nodemon` does this: https://github.com/remy/nodemon/#controlling-shutdown-of-your-script

My use-case is a `setInterval()` that I want to call `clearInterval()` on each time `micro-dev` restarts the server. Right now I end up with one interval long running for every single start/restart of the server.

**Comment by leo** [comment]
That sounds sweet!

**Comment by leo** [comment]
The thing is that we're not killing the process, but rather removing some cached files from memory and then loading the server again (which is much faster). In turn, the user wouldn't be able to handle the restart by himself. Or maybe we should send a function to call after cleanup along with the event?

**Comment by Kikobeats** [comment]
Simple way to do that:

https://github.com/Kikobeats/svr/blob/61c44191297f7e738bfa03876b4be5ba91e70b0e/bin/watch/index.js#L40

**Comment by laduke** [comment]
I have a similar use-case where I have a readstream open and when micro-dev reloads, another stream starts and the existing one doesn't get killed. I think that's what happens, anyways; The code runs number-of-restarts times. 

I guess you'd need to have dev env only related code in your service then to handle cleaning up stuff like this, which I'm not sure you'd want. 

A thing that might be nice is a "cold reloading" switch, but just using nodemon with `micro-dev -c` achieves the same thing. 

Very contrived example:
```
process.stdin.pipe(process.stdout)

module.exports = (req, res) => {
  res.end('OK!')
}
```
(type something into the same terminal micro-dev is running in and press enter. resave. repeat)

**Comment by leo** [comment]
Added in https://github.com/zeit/micro-dev/pull/48
