### ISSUE TITLE
--ignore causing "Cannot find module" for ignored directory

### ISSUE THREAD

**Issue by nickw** [vercel/micro-dev#24]
I'm building a file upload microservice and storing my temporary uploaded files in `./tmp` (for compatibility with `now`). I set up my start task to ignore this directory and it's two subdirectories (`uploads` and `downloads`):

`"dev": "micro-dev -p ${PORT:-3001} --ignore ./tmp/**",`

However when I `yarn run dev` I get an error that it `Cannot find module 'tmp/uploads'`.

Here's the full stack trace:

```
micro: Error when importing /Users/nickwientge/Desktop/process/tmp/uploads: Error: Cannot find module '/Users/nickwientge/Desktop/process/tmp/uploads'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports.file (/Users/nickwientge/Desktop/process/node_modules/micro-dev/node_modules/micro/lib/handler.js:22:11)
    at module.exports (/Users/nickwientge/Desktop/process/node_modules/micro-dev/lib/serve.js:15:55)
    at Object.<anonymous> (/Users/nickwientge/Desktop/process/node_modules/micro-dev/bin/micro-dev.js:96:1)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```

**Comment by nickw** [comment]
Ok so looks like the syntax is `--ignore=./tmp/**` with an `=` sign. But it's still not ignoring those `tmp` files when watching.

For now I just moved all my code into a `src/` directory and am using the `--watch` command instead :/

**Comment by leo** [comment]
@bakpakin Any ideas?

**Comment by bakpakin** [comment]
Try --ignore=./tmp/**/*

**Comment by bakpakin** [comment]
Try `--ignore=tmp/**/*`

**Comment by nickw** [comment]
I've already change my directory structure so for now I'll just assume your suggestion works :) I'll test again if I decide to revert my changes and re-open this issue if necessary.

**Comment by bakpakin** [comment]
I think I have found the problem and the solution. Chokidar, by default, does not know anything about our current directory - it only works with absolute paths as is. We need to pass in the current directory like so:
```javascript
const watchConfig = {
      usePolling: flags.poll,
      ignoreInitial: true,
      cwd: process.cwd(),
      ignored: [
        /\.git|node_modules|\.nyc_output|\.sass-cache|coverage/,
        /\.swp$/
      ]
    }
```
This seems to work correctly on my machine.

In the meantime, you can try the pattern `--ignore=**/tmp/**`, which will match absolute paths as well as relative paths.

**Comment by leo** [comment]
Thanks a lot for debugging, @bakpakin! Fixed [here](https://github.com/zeit/micro-dev/commit/e18532466999e96211ae925bd8595f78e6dc675c)! 😊

**Comment by leo** [comment]
@nickw Please upgrade to [1.2.1](https://github.com/zeit/micro-dev/releases/tag/1.2.1)!
