### ISSUE TITLE
micro as a peerDependency

### ISSUE THREAD

**Issue by tinchoz49** [vercel/micro-dev#31]
Hi everyone, how are you?

What do you think about define `micro` as a peerDependency?

For example, in my case I'm using micro 8.0.4 in production but when I run micro-dev I have two differents intances of `micro` working on (8.0.4 and 8.0.2) because how NPM resolve my dependencies.

This is a problem when `micro` uses some kind of internal state behaviour like this one: https://github.com/zeit/micro/blob/master/lib/index.js#L114

**Comment by timneutkens** [comment]
Seems like the right thing to do, @leo what do you think?

**Comment by sijad** [comment]
we have same issue, because of [this](https://github.com/zeit/micro/blob/dd2a4bbf506261a7b063ae51e7848e5b3ada3a5f/lib/index.js#L113-L121)
