### ISSUE TITLE
Hot-reload doesn't work with @std/esm loader

### ISSUE THREAD

**Issue by srigi** [vercel/micro-dev#37]
[@std/esm](https://github.com/standard-things/esm) is very convievent way to teach Node to load EcmaScript6+ modules. Unlike babel-register it is suited for production with almost zero overhead. You can read more about ESM in [release blogpost](https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b). 

When using micro-dev to run app written with help of ESM loader, hot-reloader doesn't pick the source files chages. Maybe the ESM's cache is somehow part of the problem, but I'm reporting it here so devs of this project gets aware of this problem.

**Comment by srigi** [comment]
Oh, false alarm. I was creating minimal "not-working" example to add to this issue. With latest version of ESM (0.10.1) it is working as expected now.

Please close, and sorry.

**Comment by timneutkens** [comment]
No worries 😄 it was most likely related to how we flush the node modules cache 👍
