### ISSUE TITLE
Prettify JSON responses

### ISSUE THREAD

**Issue by leo** [vercel/micro-dev#40]
By default, we should run them trough `JSON.stringify(obj, 0, 2)`!

**Comment by TooTallNate** [comment]
Doesn't [this already happen](https://github.com/zeit/micro/blob/ad9a5d35b3e9765e8cce2d18ccd0cd7b9160b2f0/lib/index.js#L66) when `process.env.NODE_ENV == 'development'`?

**Comment by leo** [comment]
@TooTallNate That's `micro` - but awesome observation. We need to remove it from there (so that `micro` is only for prod) and add it to `micro-dev` by default.

**Comment by kandros** [comment]
while #58 is a workaround

I tried to patch res.end but it looses the last line for some reasons, can try at https://github.com/kandros/micro-dev/blob/pretty-print-response/lib/pretty-json.js
