### ISSUE TITLE
--inspect Node Parameter

### ISSUE THREAD

**Issue by danielyogel** [vercel/micro-dev#42]
How can I use node's --inspect parameter together with micro-dev ?

Thanks.

**Comment by jamo** [comment]
Not a direct answer but something like this:
```
"scripts": {
  "debug": "node inspect ./node_modules/.bin/micro-dev -p 3000 -H 0.0.0.0 lib/index.js"
}
```

**Comment by danielyogel** [comment]
Thanks @jamo .
But I think there's a difference between `node inspect script.js` and `node script --inspect`

See here: [https://nodejs.org/en/docs/inspector/](url)

**Comment by leo** [comment]
`node --inspect ./node_modules/.bin/micro-dev -p 3000 -H 0.0.0.0 lib/index.js`

**Comment by amio** [comment]
now we have [npx](https://github.com/zkat/npx): `npx --node-args=--inspect micro-dev lib`
