### ISSUE TITLE
ignore option is not working

### ISSUE THREAD

**Issue by shigurenimo** [vercel/micro-dev#45]
Am I misunderstanding how to use it? Or is this function at development stage?

```
$ micro-dev -i ./.idea

   ┌─────────────────────────────────────────────────────┐
   │                                                     │
   │   Micro is running!                                 │
   │                                                     │
   │   • Local:            http://localhost:3000         │
   │   • On Your Network:  http://xxx.xxx.xxx.xxx:3000   │
   │                                                     │
   │   Copied local address to clipboard!                │
   │                                                     │
   └─────────────────────────────────────────────────────┘


File changed: .idea/workspace.xml - Restarting server...
Restarted!

File changed: .idea/workspace.xml - Restarting server...
Restarted!

File changed: .idea/workspace.xml - Restarting server...
Restarted!
```

**Comment by tungv** [comment]
I know this is quite confusing, but ignore paths are absolute. So you need to use `-i **/.idea`

**Comment by NetOpWibby** [comment]
This is not working for me. I even asked a mod on the Slack how to properly ignore files a few weeks ago and he had no idea. Frustrating.

**Comment by tungv** [comment]
Hi @NetOperatorWibby, can you please describe your project directory structure and what files you want to ignore?

**Comment by NetOpWibby** [comment]
Sure!

I have two folders at the base of my project, `processed` and `raw`. I dump files into the latter for transcoding or whatever and then they get dropped in the former. I want to ignore any activity those folders perform.

I tried `micro-dev -l 5mb -i processed -i raw -p ${PORT:-3000}` and variations, including adding a prefixed/appended `/` to the folder names and a couple hours ago, the tip you mentioned gave me an error about regex matching.

**Comment by tungv** [comment]
oh I see, this PR #54 broke the tip I gave above.
However, I believe you can achieve your requirement by only watching a whitelist of files.

Given your actual server logic is resided in `src` folder, you can run:

```sh
micro-dev src/index.js -l 5mb -w src -p ${PORT:-3000}
```

I'm also a heavy user of micro-dev and I agree with you that `--ignore` is not well-documented and its behavior changed a lot without notice.

**Comment by NetOpWibby** [comment]
My server logic is actually like this:

```
lib
 ... other logic
modules
 ... custom modules
processed
raw
.gitignore
index.js
package.json
README.md
```

I'm watching more than I'm ignoring so using the ignore flag would be ideal. I hadn't thought about watching though.

**Comment by tungv** [comment]
I usually put my *own logic code* into a sub directory for

1) better searching (only search within that directory)
2) cases like this, eg: watching, ignoring

If I understand correcly, the *hot codes* you want to watch for changes are inside `lib` and the root `index.js`. Since the file you start micro-dev with will always be watched, so you can just `-w lib`.

**Comment by NetOpWibby** [comment]
@tungv Forgot to reply, that seems to have worked! Thanks for the help man.

**Comment by tungv** [comment]
You're welcome pal
