### ISSUE TITLE
Enable passing flags to Node

### ISSUE THREAD

**Issue by retrixe** [vercel/micro-dev#46]
It should be possible to send flags directly to Node.js, which would enable `--inspect`, `--experimental-modules` and other such essential flags to be used in development.

**Comment by jamo** [comment]
It certainly is possible, here is a sample script with dropping flow annotations and `node inspect` while running `micro-dev`
```
    "dev": "node inspect -r ./node_modules/flow-remove-types/register.js ./node_modules/.bin/micro-dev lib/index.js",
```

**Comment by retrixe** [comment]
But won't that execute micro-dev with those flags and not the Node
application?

**Comment by timneutkens** [comment]
micro-dev loads your server file. It doesn't spawn a new Node.js instance or something similar. So what @jamo posted should work as expected 👍

**Comment by retrixe** [comment]
Huh, it seems I can't load .mjs as my entry point via micro-dev as it needs ESM to be required via CommonJS.

**Comment by Zertz** [comment]
The command above didn't seem to work for me so I used the method described in a similar issue on [micro](https://github.com/zeit/micro/issues/248#issuecomment-302955596)

```
node --inspect node_modules/.bin/micro-dev -p 3300
```

**Comment by leo** [comment]
Closing this now. Please use the solution suggested above.

**Comment by zababurinsv** [comment]
Hi. Yesterday my code worked.

server: express
node: module index.mjs
import express from "express";

const app = express();

app.get('*', (req, res) => {
res.status(200).send({key:'test'});
});

export default app

now:
{
"version": 2,
"name": "WebDav",
"builds": [
{ "src": "index.mjs", "use": "
@now
/node" }
],
"routes": [
{ "src": "/", "dest": "index.mjs" }
]
}

but today it is not work.
What's happend ?

i get an error

SyntaxError: Unexpected identifier
at Module._compile (internal/modules/cjs/loader.js:721:23)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/tmp/zeit-fun-02176ca18c0dc/___now_launcher.js:21:18)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)

How can i use *.mjs with express ?
