### ISSUE TITLE
 Trying to open unclosed connection.

### ISSUE THREAD

**Issue by sholtomaud** [vercel/micro-dev#47]
I'm using Mongoose for my server, and when micro-dev restarts it doesn't close the connection nicely so I get an error:

How would I tell micro-dev to close the connection prior to restart?

```
File changed: src/router/user.js - Restarting server...
{ Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/micro-authentication-starter/node_modules/mongoose/lib/connection.js:214:11)
...
}
```

**Comment by tungv** [comment]
You may want to ignore your schema files so it will not reload them.

Assuming you put schema files in `<project_dir>/src/models` please run micro dev with `-i **/src/models`. This will neither watch those files nor rerun them

**Comment by sholtomaud** [comment]
Thanks for the quick response! :)

I'm afraid that doesn't seem to work, I've tried a few variants, and I have models in the src folder

```
micro-dev --ignore src/models/*.js index.js 
micro-dev --ignore src/models/ index.js 
micro-dev -i ./src/models index.js 
```

I think the -i switch isn't registered as it falls over saying that "File changed: src/models/user.js", which it did.

**Comment by tungv** [comment]
since -i receive a pattern matching absolute paths, so you have to start with `**`.

Btw, if you really want to change the content of `src/models/user.js`, I don't think micro-dev hot reload model would work.

**Comment by sholtomaud** [comment]
brilliant! 👍

**Comment by daliborgogic** [comment]
@tungv

```javascript
// OverwriteModelError: Cannot overwrite `User` model once compiled.
const yesYouCan = () => mongoose.models = {}
process.on('SIGNUSR2', yesYouCan)
```

**Comment by mihaiserban** [comment]
For overwrite error the following example helped me alot. 
// OverwriteModelError: Cannot overwrite `User` model once compiled.

https://github.com/LanmeijingLucky/micro-Mongoose-example

```
const initColl = () => {
  if(mongoose.models.Log) {
    return mongoose.model('Log')
  }
  else {
    return mongoose.model('Log', LogSchema);
  }
}
module.exports = initColl();
```

**Comment by wiiiimm** [comment]
I use something like


```

const mongoose = require('mongoose');

var schema = new mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  title: Array,
  slug: String,
  fields: Array,
  definitions: Array,
  meta: {
    createdAt: Date,
    updatedAt: Date,
    publishAt: Date,
    unpublishAt: Date
  }
});

const getModel = () => {
  if (mongoose.models.Page) {
    return mongoose.model('Page')
  } else {
    return mongoose.model('Page', schema, 'Pages');
  }
}

module.exports = getModel()


```



```
const Page = require('./dbSchema.js');

Page.find((err, data) => {...

```
