### ISSUE TITLE
Add options for explicitly including/excluding what to watch on restart

### ISSUE THREAD

**Issue by ansballard** [vercel/micro-dev#5]
So I'm trying out `micro-dev` on an existing project, and I don't have a way to ignore changes in files that don't have to do with micro. The error comes from:

```js
  /* listening.js, Line 42 */
  // Remove file that changed from the `require` cache
  for (const item of toDelete) {
    const location = require.resolve(item)
    delete require.cache[location]
  }
```

`Cannot find module <insert existing js files here>`. I know this is a minimalist library, but it would be nice to at least be able to specify a single file to run and watch. It looks like the watch gets directories here:

```js
  /* listening.js, Line 74 */
  const closestPkg = await pkgUp(path.dirname(file))
  const toWatch = closestPkg ? path.dirname(closestPkg) : process.cwd()
```

So if there was another cli arg (--watch?) that got passed as `toWatch`, possibly with some glob magic, I think that would work for my use case. Let me know if I missed any details! Awesome lib!

**Comment by timneutkens** [comment]
Lets track this in #4 (same error)

**Comment by ansballard** [comment]
Works for me!
