### ISSUE TITLE
Increase JSON parse limit globally

### ISSUE THREAD

**Issue by mrcageman** [vercel/micro-dev#51]
Recently opened this issue: [Handling multipart/formdata requests (Body exceeded 1mb limit)](https://github.com/zeit/micro/issues/318)

Turned out that this was related to using `micro-dev`, rather than micro itself. Up till now I have not been able to find a way to increase the 1mb limitation on `micro-dev` without altering the package itself.

Any options there?

**Comment by sbr464** [comment]
Yes please, wasted 30 mins on this

**Comment by sbrichardson** [comment]
I added a pull request for this change, it had affected me also. Can you check it out?
