### ISSUE TITLE
Ignore flag not working correctly

### ISSUE THREAD

**Issue by orf** [vercel/micro-dev#56]
This is very annoying. My IDE puts a `.idea` file in the project, which is in my gitignore. `micro-dev` does not seem to respect the `--ignore` flag. I have tried:

`--ignore=.idea/`

`--ignore=.idea/*`

`--ignore=**/*.xml`

`--ignore=*.xml`

And all other kinds of patterns. Unfortunately combined with https://github.com/zeit/micro-dev/issues/55 it makes `micro-dev` pretty unusable right now :'(

**Comment by leo** [comment]
Can you try cloning https://github.com/zeit/micro-dev/pull/54? Maybe it solves your issue? If so, we can release it 😊

**Comment by orf** [comment]
Yes, this fixes my issue! 👍

**Comment by leo** [comment]
Fixed in https://github.com/zeit/micro-dev/pull/54

**Comment by orf** [comment]
Thank you for the fast turn-around @leo 👍

**Comment by leo** [comment]
[Released!](https://github.com/zeit/micro-dev/releases/tag/2.0.0) 😊
