### ISSUE TITLE
Howto trap exit signal to cleanup

### ISSUE THREAD

**Issue by brikou** [vercel/micro-dev#60]
Is there a way to trap signal on reloading in order to do some cleanup?

It seems that micro-dev does not trigger usr signal and so I cannot do trap.

see https://stackoverflow.com/questions/14031763/doing-a-cleanup-action-just-before-node-js-exits (which does not work)

**Comment by tungv** [comment]
It sends sigusr2 when restarting

**Comment by brikou** [comment]
Thank you, I'll give a try :+1:

**Comment by brikou** [comment]
It works with my pr, see #61
