### ISSUE TITLE
Best way to get automatic refresh of browser on hot reload?

### ISSUE THREAD

**Issue by bestwestern** [vercel/micro-dev#62]
As the subject says - how do I avoid pressing f5 every time I change the code?

**Comment by tungv** [comment]
I want to understand more about your situation. What shows up in the browser when you refresh? A html website or a JSON api response?

**Comment by bestwestern** [comment]
Sorry for the vague request.

1. How could I run the micro socket io example with micro-dev?
(https://github.com/zeit/micro/tree/master/examples/socket.io-chat-app)

If it is possible I would like to have the server reload on code change AND the browser to refresh

**Comment by tungv** [comment]
Hi @bestwestern,
As I understand, micro is used programmatically in  the example above. That way of using micro is not supported by micro-dev. So you won't be able to run that example with micro-dev.

In general, unless your "main" file exports a handler function or a promise that resolves to that function,  you won't be able to use micro-dev

**Comment by leo** [comment]
Thanks for the explanation @tungv. I'm going to close this now, as it's clearly out of scope for this project. In development, you shouldn't use the browser to preview the response of your API - use a command line tool like `curl`.

In turn, there's no need to refresh the browser.
