### ISSUE TITLE
now-secrets.json does not work for dev mode.

### ISSUE THREAD

**Issue by joonhocho** [vercel/micro-dev#68]
now-secrets.json does not work for dev mode, but it works for production mode.

`now secrets add` also doesn't work.

**Comment by sergiodxa** [comment]
I have used now-env with micro-dev without issues, could you explain more? Or create a repo to reproduce it

**Comment by joonhocho** [comment]
@sergiodxa I did install `now-env` and it works. Should it be added by default?

**Comment by sergiodxa** [comment]
No, if you want to use it you need to manually install it and load it.
