### ISSUE TITLE
what's with the favicon?

### ISSUE THREAD

**Issue by codeofsumit** [vercel/micro-dev#75]
Hi there,

I'm trying out micro-dev and loving it so far. But every time I refresh the browser and the service/functionruns again, there are two requests. The one from the browser, and the one from the favicon.
It's also trashing my terminal. Can this be avoided?

Using this right now:

```
if (req.url === '/favicon.ico') {
  res.end();
}
```

![image](https://user-images.githubusercontent.com/2399810/37867507-bbd67496-2f99-11e8-82be-2a9348071037.png)

**Comment by timneutkens** [comment]
Browsers look for /favicon.ico and request it when loading the page, not much we can do about that. I'm also not comfortable with hiding the requests, since people might not know that request is there 😅

Personally I'd use either `curl` or https://www.getpostman.com/ if you need a UI.

**Comment by paulogdm** [comment]
I would also check [Insomnia](https://insomnia.rest/). 
It is opensource ([repo](https://github.com/getinsomnia/insomnia)) and a good alternative to postman!

**Comment by codeofsumit** [comment]
will do, stupid browsers 🙄 
thanks!
