### ISSUE TITLE
Graceful shutdown on SIGTERM

### ISSUE THREAD

**Issue by ericf** [vercel/micro-dev#9]
It's great that `micro` core now handles `SIGTERM`, and it would be even better if `micro-dev` did as well. Better yet if both `micro` and `micro-dev` handled `SIGINT` too to gracefully shut down 😎

**Comment by leo** [comment]
@rauchg and I talked extensively about this. Graceful shutdown doesn't make sense in development, because it takes a lot of times to close down all open sockets. In turn, neither fast hot reloading, nor quitting the server and not having to wait for a long time works. I hope you understand... 😊

**Comment by ericf** [comment]
Hot reloading gets rid of most of the need to repeatedly shutdown the server in dev, so that's why I was thinking it would be fine to add graceful shutdown for `micro-dev` process too.

My use case is running `micro-dev` in a Docker container. I would love for it to be shutdown gracefully instead of having to be `docker kill`'d.

**Comment by leo** [comment]
@rauchg Can you jump in?

Guillermo had the same concern, but then he said that there are several different ways to handle such a situation with Docker - so that `SIGTERM` doesn't need to be handled.

**Comment by ericf** [comment]
Maybe the idea is to use the `docker run --init` option to manage the node process.
